In [2]:
#NUMPY

Installation & importing

In [3]:
#pip install numpy

import numpy as np

# 1. Array Creation

In [41]:
a=np.array([[1,2,3],[4,5,6]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)
print("Item size (bytes):", arr.itemsize)
print("Total bytes:", arr.nbytes)
print("Transpose:\n", arr.T)

a1=np.arange(0, 10, 2)
a2=np.linspace(0,1,11) 
a3=np.logspace(0, 3, 4,base =2)
a4=np.zeros((3,4))
a5=np.ones((2,2))
a6=np.empty((2,3))
a7=np.full((2,2), 7)
a8=np.eye(4)


print(a)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
print(a7)
print(a8)



Shape: (5,)
Size: 5
Dimensions: 1
Data Type: float32
Item size (bytes): 4
Total bytes: 20
Transpose:
 [1. 2. 3. 4. 5.]
[[1 2 3]
 [4 5 6]]
[0 2 4 6 8]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[1. 2. 4. 8.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[2.12199579e-314 6.36598737e-314 1.06099790e-313]
 [1.48539705e-313 1.90979621e-313 2.33419537e-313]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Reading Data with NumPy

numpy.fromfile(file, dtype=float, count=-1, sep='', offset=0)

numpy.loadtxt(fname, dtype=float, comments='#', delimiter=None,
              converters=None, skiprows=0, usecols=None, unpack=False)

data = np.loadtxt('data.csv', delimiter=',', usecols=(0, 2))

arr = np.load('array.npy')   # load one array

data = np.load('arrays.npz') # multiple arrays

np.save('array.npy', arr)      # saves a single array

np.savez('arrays.npz', a=arr1, b=arr2)  # saves multiple arrays



dtypes (data types)

# 2. Data type

In [9]:
x = np.array([1,2,3], dtype=np.int64)
x.astype(np.float32)

array([1., 2., 3.], dtype=float32)



# 3. Indexing & Slicing

In [19]:
a = np.arange(12).reshape(3,4)
print(a)
row = a[0]
print(row)
sub=a[:,1:3]
print(sub)
sub[0,0] = 999
print(sub)

a[[0,2], [1,3]]
print(a)

mask = a % 2 == 0
a[mask] # 1D array of matched elements (copy)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[999   2]
 [  5   6]
 [  9  10]]
[[  0 999   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


array([ 0,  2,  4,  6,  8, 10])

# 4. Reshape & Transpose

In [28]:
reshaped = arr2d.reshape(4,3)
flattened_view = arr2d.ravel()
flattened_copy = arr2d.flatten()
print('reshaped:',reshaped)
print('Transposed:', reshaped.T)
print("flattened_view",flattened_view)
print("flattened_copy",flattened_copy)
print('Swap axes:', np.swapaxes(arr2d,0,1))
print('Swap axes:', np.swapaxes(arr2d,0,1).shape)

reshaped: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Transposed: [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
flattened_view [ 0  1  2  3  4  5  6  7  8  9 10 11]
flattened_copy [ 0  1  2  3  4  5  6  7  8  9 10 11]
Swap axes: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Swap axes: (4, 3)


# 5. Concatenation & Stacking

In [40]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
print(a+b)
concat = np.concatenate([a,b], axis=0)
print(concat)
vstacked = np.vstack([a,b])
print(vstacked)
hstacked = np.hstack([a,b])
print(hstacked)
stacked = np.stack([a,b], axis=0)
print(stacked)
splits = np.split(concat,2,axis=0)
print(splits)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# 6. Mathematical Functions

In [43]:
arr=np.array([[1,2,3],[4,5,6]])
print("Addition +2:\n", arr + 2)
print("Multiplication *3:\n", arr * 3)
print("Square:\n", np.square(arr))
print("Square Root:\n", np.sqrt(arr))
print("Absolute:\n", np.abs(arr - 5))

# Trigonometric
angles = np.array([0, np.pi/2, np.pi])
print("sin:", np.sin(angles))
print("cos:", np.cos(angles))
print("tan:", np.tan(angles))

# Exponential / Log
exp_arr = np.array([1, 2, 3])
print("exp:", np.exp(exp_arr))
print("log:", np.log(exp_arr))
print("log10:", np.log10(exp_arr))


Addition +2:
 [[3 4 5]
 [6 7 8]]
Multiplication *3:
 [[ 3  6  9]
 [12 15 18]]
Square:
 [[ 1  4  9]
 [16 25 36]]
Square Root:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Absolute:
 [[4 3 2]
 [1 0 1]]
sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
exp: [ 2.71828183  7.3890561  20.08553692]
log: [0.         0.69314718 1.09861229]
log10: [0.         0.30103    0.47712125]


# 6. Statistical Functions

In [55]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Sum:", np.sum(arr))
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Product",np.prod(arr))
print("std Dev",np.std(arr))
print("varaince",np.var(arr))
print("Min",np.min(arr))
print("Max",np.max(arr))
print("Cumulative Sum:", np.cumsum(arr))
print("Cumulative Product:", np.cumprod(arr))

Sum: 45
Mean: 5.0
Median: 5.0
Product 362880
std Dev 2.581988897471611
varaince 6.666666666666667
Min 1
Max 9
Cumulative Sum: [ 1  3  6 10 15 21 28 36 45]
Cumulative Product: [     1      2      6     24    120    720   5040  40320 362880]


# 7. Linear Algebra

In [57]:
matrix = np.array([[7,3],[3,-1]])
print("Dot product:\n", np.dot(matrix, matrix))
print("Matrix Multiplication:\n", np.matmul(matrix, matrix))
print("Determinant:", np.linalg.det(matrix))
print("Inverse:\n", np.linalg.inv(matrix))
eigvals, eigvecs = np.linalg.eig(matrix)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)
print("Trace:", np.trace(matrix))


Dot product:
 [[58 18]
 [18 10]]
Matrix Multiplication:
 [[58 18]
 [18 10]]
Determinant: -15.999999999999998
Inverse:
 [[ 0.0625  0.1875]
 [ 0.1875 -0.4375]]
Eigenvalues: [ 8. -2.]
Eigenvectors:
 [[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]
Trace: 6


# 8. Set Operations

In [59]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])
print("Unique:", np.unique(arr2))
print("Intersection:", np.intersect1d(arr1, arr2))
print("Union:", np.union1d(arr1, arr2))
print("Difference:", np.setdiff1d(arr1, arr2))
print("Difference:", np.setdiff1d(arr2, arr1))
print("Symmetric difference:", np.setxor1d(arr1, arr2))


Unique: [3 4 5 6]
Intersection: [3 4]
Union: [1 2 3 4 5 6]
Difference: [1 2]
Difference: [5 6]
Symmetric difference: [1 2 5 6]
